---
- hosts: all
  tasks:
    - name: does the apps exist
      shell: dokku apps:exists {{ item.app_name }}
      register: apps_exist
      ignore_errors: True
      loop: "{{ app_data }}"

    - name: create apps
      shell: dokku apps:create {{ item.item.app_name }}
      when: item.rc != 0
      loop: "{{ apps_exist.results }}"

    - name: set env
      shell: dokku config:set {{ item.app_name }} {{ item.app_env }} --no-restart
      when: item.app_env
      loop: "{{ app_data }}"

    - name: set Dockerfile path
      shell: dokku builder-dockerfile:set {{ item.app_name }} dockerfile-path {{ item.dockerfile }}
      loop: "{{ app_data }}"

    - name: turn on https
      shell: dokku letsencrypt:active {{ item.app_name }} || dokku letsencrypt:enable {{ item.app_name }}
      loop: "{{ app_data }}"
