FROM node:20 as build
WORKDIR /app
COPY ./kitten /app
RUN npm install && npx nuxt build

FROM node:20
WORKDIR /app
COPY --from=build /app/.output ./
EXPOSE 5000
ENV HOST=0.0.0.0 PORT=5000 NODE_ENV=production

CMD ["node","/app/server/index.mjs"]