dokku:
  hosts: "{{ lookup('ansible.builtin.env', 'DOKKU_HOST') }}"
  vars:
    app_data:
      - {
          app_name: "stage-api",
          app_env: "{{ lookup('ansible.builtin.env', 'STAGE_API_ENV', default='') }}",
          dockerfile: "deploy/Dockerfile.api",
        }
      - {
          app_name: "stage-front",
          app_env: "{{ lookup('ansible.builtin.env', 'STAGE_API_FRONT', default='') }}",
          dockerfile: "deploy/Dockerfile.front",
        }
