---
name: 'deploy'

on:
  workflow_dispatch:
  push:
    branches:
      - dev

jobs:
  pre_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        env:
          DOKKU_HOST: ${{ secrets.DOKKU_HOST }}
        with:
          playbook: ${{ github.workspace }}/deploy/app.yaml
          key: ${{secrets.SSH_PRIVATE_KEY}}
          options: |
            --inventory ${{ github.workspace }}/deploy/hosts.yaml
            -u root
  deploy:
    runs-on: ubuntu-latest
    needs: pre_deploy
    steps:
      - name: Cloning repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Push to dokku api
        uses: dokku/github-action@master
        with:
          git_remote_url: 'ssh://dokku@kittensanswers.ru:22/stage-api'
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Push to dokku front
        uses: dokku/github-action@master
        with:
          git_remote_url: 'ssh://dokku@kittensanswers.ru:22/stage-front'
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
