---
name: "install"

on:
  workflow_dispatch:

jobs:
  start:
    runs-on: ubuntu-latest
    steps:
      - name: multiple command
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: kittensanswers.ru
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo apt-add-repository -y ppa:ansible/ansible
            sudo apt-get update
            sudo apt-get install -y ansible git
            wget https://raw.githubusercontent.com/dokku/dokku/master/bootstrap.sh
            sudo bash bootstrap.sh
