---
name: "start"

on:
  workflow_dispatch:

jobs:
  start:
    runs-on: ubuntu-latest
    steps:
      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          # Required, playbook filepath
          playbook: deploy/app.yml
          # Optional, SSH private key
          key: ${{secrets.SSH_PRIVATE_KEY}}
          options: |
            --inventory deploy/hosts
            -u root
