---
name: "start"

on:
  workflow_dispatch:

jobs:
  start:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: ${{ github.workspace }}/deploy/app.yml
          key: ${{secrets.SSH_PRIVATE_KEY}}
          options: |
            --inventory ${{ github.workspace }}/deploy/hosts
            -u root
